#!/bin/bash

echo "Installing jq"
curl -L -o ./jq "$(curl -s "https://api.github.com/repos/stedolan/jq/releases/latest" | grep browser_download_url | grep 'jq-linux64' | cut -d '"' -f 4)"
chmod +x ./jq

echo "Getting 10 latest bwip-js versions"
docker run --rm node:lts-slim npm view bwip-js versions --json | ./jq -r '.[]' | tail -n 10 > versions.txt

echo "Building images"
cat versions.txt | while read VERSION
do
    LATEST_VERSION="$(cat versions.txt | tail -n 1)"

    if [ $VERSION=$LATEST_VERSION ]
    then
        docker build --build-arg VERSION=${VERSION} -t "${DOCKER_REPO}:${VERSION}" -t "${DOCKER_REPO}:latest" .
    else
        docker build --build-arg VERSION=${VERSION} -t "${DOCKER_REPO}:${VERSION}" .
    fi
done
