name: docker-hub-build

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker Hub Build
        env: 
          DH_TRIGGER_URL: ${{ secrets.DH_TRIGGER_URL }}
        run: curl -s -X POST $DH_TRIGGER_URL > /dev/null
